### ISSUE TITLE
waiting paper list (CVPR 2019)

### ISSUE THREAD

**Issue by hwalsuklee** [hwalsuklee/awesome-deep-text-detection-recognition#1]
### Detection
- [x] [Arbitrary Shape Scene Text Detection with Adaptive Text Region Representation](https://arxiv.org/pdf/1905.05980.pdf)

### Recognition
 - [x] [Sequence-to-Sequence Domain Adaptation Network for Robust Text Image Recognition](http://openaccess.thecvf.com/content_CVPR_2019/papers/Zhang_Sequence-To-Sequence_Domain_Adaptation_Network_for_Robust_Text_Image_Recognition_CVPR_2019_paper.pdf)

- [x] [Aggregation Cross-Entropy for Sequence Recognition](https://arxiv.org/pdf/1904.08364.pdf)
https://github.com/summerlvsong/Aggregation-Cross-Entropy

- [x] [ESIR: End-to-end Scene Text Recognition via Iterative Image Rectification](https://arxiv.org/pdf/1812.05824.pdf)

### ETC
Text Effect
- [x] [Typography with Decor: Intelligent Text Style Transfer](http://openaccess.thecvf.com/content_CVPR_2019/papers/Wang_Typography_With_Decor_Intelligent_Text_Style_Transfer_CVPR_2019_paper.pdf)
https://daooshee.github.io/Typography2019/

Keyword spotting
- [x] [An Alternative Deep Feature Approach to Line Level Keyword Spotting](http://openaccess.thecvf.com/content_CVPR_2019/papers/Retsinas_An_Alternative_Deep_Feature_Approach_to_Line_Level_Keyword_Spotting_CVPR_2019_paper.pdf)

Handwritten
- [x] [Handwriting Recognition in Low-resource Scripts using Adversarial Learning](https://arxiv.org/pdf/1811.01396.pdf)
https://github.com/AyanKumarBhunia/Handwriting_Recogition_using_Adversarial_Learning

**Comment by hwalsuklee** [comment]
## CVPR 2019
ESIR: End-to-end Scene Text Recognition via Iterative Image Rectification
Sequence-to-Sequence Domain Adaptation Network for Robust Text Image R?
Learning Shape-Aware Embedding for Scene Text Detection
DynTypo: Example-based Dynamic Text Effects Transfer
Typography with Decor: Intelligent Text Style Transfer

**Comment by ayumiymk** [comment]
ESIR: End-to-end Scene Text Recognition via Iterative Image Rectification

**Comment by hwalsuklee** [comment]
all papers were included to readme.md
