### ISSUE TITLE
作者你好，这个仓库多久更新一次？

### ISSUE THREAD

**Issue by liuzhuang1024** [hwalsuklee/awesome-deep-text-detection-recognition#10]

**Comment by dhkim0225** [comment]
This repository usally updates contents one or two months after the end of the main ai conference.

**Comment by dhkim0225** [comment]
Sorry for late reply.

This repository used to update contents after one of major conference (ICCV, AAAI, CVPR, NeurIPs, ...) is completely finished.

And... Please use English.

Regards,
Anthony

**Comment by liuzhuang1024** [comment]
Sorry, I thought you were Chinese.Thank you for the reply very much.
